<a href="https://colab.research.google.com/github/Spicyredd/Learn_PyTorch/blob/master/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch Fundamentals

Resource notebook: https: //www.learnpytorch.io/00_pytorch fundamentals

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions



In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensors
### Creating tensors
Pytorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html



In [2]:
# Scalar tensor

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                         [3,6,7],
                         [7,2,6]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [7, 2, 6]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [7, 2, 6]])

In [16]:
TENSOR2 = torch.tensor([
                        [[62,624,52],
                         [52,73,37],
                         [634,23,73],
                         [234,5234,624]],
                        [[423,6234,624],
                         [534,645,73],
                         [345,745,234],
                         [34,624,624]]
                        ])
TENSOR2

tensor([[[  62,  624,   52],
         [  52,   73,   37],
         [ 634,   23,   73],
         [ 234, 5234,  624]],

        [[ 423, 6234,  624],
         [ 534,  645,   73],
         [ 345,  745,  234],
         [  34,  624,  624]]])

In [17]:
TENSOR2.shape

torch.Size([2, 4, 3])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://docs.pytorch.org/docs/main/generated/torch.rand.html

In [18]:
# Create a random tensor of size
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3041, 0.5948, 0.7970, 0.4174],
        [0.1550, 0.5504, 0.0790, 0.5369],
        [0.6847, 0.3140, 0.4722, 0.9349]])

In [19]:
random_tensor.ndim

2

In [20]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
random_tensor_2 = torch.rand(size=(34,324,523))
random_tensor_2.shape

torch.Size([34, 324, 523])

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [26]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [27]:
# Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device the tensor is created for
                               requires_grad=False) # whether tensor takes part in back propagation or not

float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

### Precision in computing-
https://en.wikipedia.org/wiki/Precision_(computer_science)

In [30]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16, # what datatype is the tensor
                               device=None, # what device the tensor is created for
                               requires_grad=False)

In [31]:
float_16_tensor.dtype

torch.float16

In [32]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [33]:
int_32_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.int32, # what datatype is the tensor
                               device=None, # what device the tensor is created for
                               requires_grad=False)

In [34]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [35]:
long_tensor = torch.tensor([3, 6, 9],
                            dtype=torch.long, # what datatype is the tensor
                            device=None, # what device the tensor is created for
                            requires_grad=False)

In [36]:
float_32_tensor * long_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [37]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3147, 0.2966, 0.3016, 0.0315],
        [0.5535, 0.5099, 0.5825, 0.5397],
        [0.6201, 0.5355, 0.6255, 0.6009]])

In [38]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.3147, 0.2966, 0.3016, 0.0315],
        [0.5535, 0.5099, 0.5825, 0.5397],
        [0.6201, 0.5355, 0.6255, 0.6009]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [39]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [41]:
tensor

tensor([1, 2, 3])

In [42]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [43]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [44]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix Multiplicaiton (dot product)

More information in multiplying matrices -https://www.mathsisfun.com/algebra/matrix-multiplying.html
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2,3) @ (3,2)` -> `(2,2)`
* `(3,2) @ (2,3)` -> `(3,3)`

In [45]:
torch.matmul(torch.rand(10, 10), torch.rand(10, 10)).shape

torch.Size([10, 10])

In [46]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [47]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [48]:
tensor

tensor([1, 2, 3])

In [49]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [50]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
print(value)

tensor(12)
CPU times: user 1.18 ms, sys: 0 ns, total: 1.18 ms
Wall time: 3.45 ms


In [51]:
%%time
torch.matmul(tensor, tensor)
print(value)

tensor(12)
CPU times: user 621 µs, sys: 0 ns, total: 621 µs
Wall time: 3.53 ms


### One of the most common error in deep learning: Shape errors

Visualize matrix multiplication - http://matrixmultiplication.xyz/

In [52]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [53]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**. A **transpose**: switches the axes or dimensions of a given tensor

In [54]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [55]:
tensor_B.T , tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [56]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape; {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape; torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [57]:
# Create a tensor
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
  # Find the min
  torch.min(x), x.min()

(tensor(1), tensor(1))

In [59]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [60]:
# Find the mean - note: the torch.mean() function requires a tensor of float datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [61]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

In [62]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value
x.argmin()

tensor(0)

In [63]:
x[0]

tensor(1)

In [64]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [65]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combing multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [66]:
# Let's create a tensor
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [67]:
# Add an extra dimension
x_reshaped = x.reshape((1,9))
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [68]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [69]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [70]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9],
        [5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
# torch.squeeze() - removes all single dimensions from a tensor
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x)
y.size()
torch.Size([2, 2, 2])
y = torch.squeeze(x, 0)
y.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x, 1)
y.size()
torch.Size([2, 2, 1, 2])
y = torch.squeeze(x, (1, 2, 3))
torch.Size([2, 2, 2])

torch.Size([2, 2, 2])

In [72]:
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])

New Tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [73]:
# torch.unsqueeze() - add a single dimension to a tensor at specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previous shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nPrevious target: {x_unsqueezed}')
print(f'Previous shape: {x_unsqueezed.shape}')

Previous target: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
Previous shape: torch.Size([9])

Previous target: tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])
Previous shape: torch.Size([1, 9])


In [74]:
# torch.permute - rearranges the dimensions of a tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [heigth, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f'Previous shape: {x_original.shape}')
print(f'New shape: {x_permuted.shape}') # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy

In [75]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [76]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [77]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [78]:
# Let's index on the most inner bracket (last dimension)
x[0][2][1]

tensor(8)

In [79]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [80]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [81]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [82]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [83]:
# Index on x to return 0
x[0, 2, 2]

# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors and Numpy
NumPy is a popular scientific Python numerical computing library.

And beacause of this, PyTorch has functionality to interact with it.

* Data in NumPy, wan tin PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [84]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # Default datatype of numpy arrays is float64 while torch's default datatype is float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [85]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy() # when converting to the tensor to a numpy array the numpy array takes the dtype of the tensor torch.float32 -> float32
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [87]:
# Update the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a
**random seed**

Essentially what the random seed does is "flavour" the randomness.

In [88]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.3193, 0.9508, 0.1836, 0.8556],
        [0.0824, 0.1226, 0.4550, 0.6672],
        [0.2776, 0.4677, 0.3394, 0.3526]])
tensor([[0.2811, 0.6428, 0.3739, 0.8081],
        [0.8823, 0.7833, 0.2744, 0.9578],
        [0.4578, 0.1960, 0.2565, 0.9785]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [89]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:

* https://docs.pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia,org/wiki/Random_seed


## Running tensors and PyTorchobjets on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scens to make everything hunky dory (good).

### 1.Getting a GPU

1. Easiest - Use Google Collab for free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options ... Info on - https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/#more-6
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent
computers on the cloud and access them


For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this,
refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [90]:
!nvidia-smi

Tue May 13 14:52:19 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   60C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [91]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU


In [92]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [93]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [95]:
# Create a tensor (default on the CPU)

tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [97]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [98]:
# If tensor in on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [99]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & Curriculum